version: '3.2'
services:
  bikeconsumer:
    build: .
    volumes:
     - ./src:./src/Consumer
    ports:
     - "5000:5000"
    labels:
      name: "Consumer for Dublin Bikes Job"
      role: "Consumer App"
